#!/usr/bin/env bash

usage="$(basename "$0") [-h] [PATH] -- Reveals code tags in a directory

where:
    -h show this help text"

if [ "$1" == "-h" ]; then
    echo "$usage"
    exit 0
fi

grep -nEro '(\s|^)(#|\*|/\*|//) ?[A-Z\?\!]+:.*' $1 | gawk '
    match($0, /^([^:]*):([0-9]+):[^A-Z\?\!]+(.+)$/, a){
        printf"\033[35m%s\033[36m:%s \033[32m\033[1m%s\033[0m\n",
            a[1], a[2], a[3]
    }'
